=head1 Perl::Tutorial

Perl::Tutorial is a tutorial for Perl.

=head1 Contributing

Fork the repository on Github:

  https://github.com/copperly/Perl-Tutorial

Pull requests gladly accepted!

=head1 Copyright and License

Copyright (C) 2011 Copperly Ltd.

This module is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
